# Generated by Django 5.1.1 on 2024-10-02 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_cliente_direccion_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('minorista', 'Minorista'), ('mayorista', 'Mayorista')], max_length=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='descripcion',
            field=models.CharField(max_length=20, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.BigIntegerField(unique=True),
        ),
    ]
