# Generated by Django 5.1.1 on 2024-10-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_insumo_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='registrado_por',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.IntegerField(unique=True),
        ),
    ]
