# Generated by Django 5.1.1 on 2024-10-02 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_remove_proveedor_registrado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='descripcion',
            field=models.CharField(max_length=20, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.BigIntegerField(unique=True),
        ),
    ]
