# Generated by Django 5.1.1 on 2024-10-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_proveedor_registrado_por_alter_insumo_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='temperatura_conservacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
