# Generated by Django 5.1.1 on 2024-10-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_producto_temperatura_conservacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreria.cliente'),
        ),
    ]
