# Generated by Django 5.1.1 on 2024-10-08 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_transaccion_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.cliente'),
        ),
    ]
