# Generated by Django 5.1.1 on 2024-10-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
