# Generated by Django 5.1.1 on 2024-10-10 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0014_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('leche', 'Leche'), ('queso', 'Queso'), ('yogurt', 'Yogurt'), ('mantequilla', 'Mantequilla'), ('crema', 'Crema'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_elaboracion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='lote',
            field=models.CharField(default='lote_default', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('kilogramo', 'Kilogramo (kg)'), ('gramo', 'Gramo (g)'), ('litro', 'Litro (l)'), ('mililitro', 'Mililitro (ml)'), ('unidad', 'Unidad')], default='unidad', max_length=15),
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
