# Generated by Django 5.1.1 on 2024-10-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_remove_transaccion_producto_transaccion_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.producto'),
        ),
    ]
