# Generated by Django 5.1.1 on 2024-10-15 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0023_remove_transaccion_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_elaboracion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
