# Generated by Django 5.1.1 on 2024-10-16 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0025_cliente_documento_cliente_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
