# Generated by Django 5.1.1 on 2024-10-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0026_cliente_registrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('cedula de ciudadania', 'Cédula de ciudadanía'), ('tarjeta de identidad', 'Tarjeta de identidad'), ('cedula de extranjeria', 'Cédula de extranjería'), ('pasaporte', 'Pasaporte'), ('nit', 'Número de Identificación Tributaria (NIT)')], default='cedula_ciudadania', max_length=21),
        ),
    ]
