# Generated by Django 5.1.1 on 2024-10-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0029_alter_cliente_registrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tipo_persona',
            field=models.CharField(choices=[('juridica', 'Persona Jurídica'), ('natural', 'Persona Natural')], default='natural', max_length=10, verbose_name='Tipo de Persona'),
        ),
    ]
