# Generated by Django 5.1.1 on 2024-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0030_proveedor_tipo_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_persona',
            field=models.CharField(choices=[('Persona Jurídica', 'Persona Jurídica'), ('Persona Natural', 'Persona Natural')], default='natural', max_length=16, verbose_name='Tipo de Persona'),
        ),
    ]
