# Generated by Django 5.1.1 on 2024-10-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0032_insumo_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('Kilogramo', 'Kilogramo (kg)'), ('Gramo', 'Gramo (g)'), ('Litro', 'Litro (l)'), ('Mililitro', 'Mililitro (ml)'), ('Unidad', 'Unidad')], default='Unidad', max_length=15),
        ),
    ]
