# Generated by Django 5.1.1 on 2024-10-18 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0037_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.producto'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(default='Descripción', max_length=50),
        ),
    ]
