# Generated by Django 5.1.1 on 2024-10-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0043_alter_transaccion_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='productos',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='producto',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
