# Generated by Django 5.1.1 on 2024-10-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0044_remove_transaccion_productos_transaccion_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='producto',
            new_name='productos',
        ),
    ]
