# Generated by Django 5.2.7 on 2025-10-27 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0047_remove_transaccion_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='monto',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='productos_json',
            field=models.JSONField(default=dict, verbose_name='Productos'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(default='Descripción', max_length=255),
        ),
        migrations.DeleteModel(
            name='LineaTransaccion',
        ),
    ]
