# Generated by Django 5.2.7 on 2025-10-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0048_remove_transaccion_monto_transaccion_monto_total_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Backup',
        ),
    ]
