# Generated by Django 5.2.7 on 2025-11-05 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0049_delete_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.insumo'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.proveedor'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.cliente'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='productos_json',
            field=models.JSONField(default=dict),
        ),
    ]
