# Generated by Django 5.2.7 on 2025-11-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0050_transaccion_insumo_transaccion_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='insumo',
        ),
        migrations.AddField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='productos_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
