# Generated by Django 5.2.7 on 2025-11-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0051_alter_transaccion_options_remove_transaccion_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
    ]
