# Generated by Django 5.2.7 on 2025-11-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0052_alter_insumo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
