# Generated by Django 5.2.7 on 2025-11-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0053_alter_insumo_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
