# Generated by Django 5.2.7 on 2025-12-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0054_remove_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
